# SPDX-License-Identifier: GPL-2.0


dtb-$(CONFIG_ARCH_SUNXI) += \
	sun55i-t527-disable_uart0.dtbo \
	sun55i-t527-spidev1_0.dtbo \
	sun55i-t527-spidev1_1.dtbo \
	sun55i-t527-i2c1.dtbo \
	sun55i-t527-i2c2.dtbo \
	sun55i-t527-i2c4.dtbo \
	sun55i-t527-uart2.dtbo \
	sun55i-t527-uart3.dtbo \
	sun55i-t527-uart4.dtbo \
	sun55i-t527-uart5.dtbo \
	sun55i-t527-uart6.dtbo \
	sun55i-t527-uart7.dtbo \
	sun55i-t527-uart8.dtbo \
	sun55i-t527-usb3.0.dtbo \
	sun55i-t527-pcie.dtbo 

